### PR TITLE
fix: config dev port (fix #317)

### LINKED ISSUE #317: Configuration server port not working
### Describe the bug

Server port defined in vite or histoire config file are not take into account with dev mode.

### Reproduction

-

### System Info

```shell
-
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hugoattal**
### Description

Dev port was always 6006 when not defined in the command line

### Additional context

Example histoire config:

```ts
// vite.config.js
/// <reference types="histoire" />

import { defineConfig } from 'vite'

export default defineConfig({
  // ...
  histoire: {
    vite: {
      server: {
        port: 1980,
      },
    },
  },
})

```

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### CODE REVIEW

File: packages/histoire/src/node/server.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ import { useModuleLoader } from './load.js'
 import { wrapLogError } from './util/log.js'
 import { createMarkdownFilesWatcher, onMarkdownListChange } from './markdown.js'
 
-export async function createServer (ctx: Context, port: number) {
+export async function createServer (ctx: Context, config: {port?: number} = {}) {
```
Comment (Akryum) [inline packages/histoire/src/node/server.ts:12]:
```suggestion
export interface CreateServerOptions {
  port?: number
}

export async function createServer (ctx: Context, options: CreateServerOptions = {}) {
```

File: packages/histoire/src/node/server.ts [hunk 2]
```diff
@@ -36,7 +36,7 @@ export async function createServer (ctx: Context, port: number) {
   }
 
   // Wait for pre-bundling (in `listen()`)
-  await server.listen(port)
+  await server.listen(config.port ?? server.config.server?.port ?? 6006)
```
Comment (Akryum) [inline packages/histoire/src/node/server.ts:39]:
```suggestion
  await server.listen(options.port ?? server.config.server?.port ?? 6006)
```

**Review by Akryum — CHANGES_REQUESTED** [review]

File: packages/histoire/src/node/server.ts (hunk 1 above)
Comment (hugoattal) [reply packages/histoire/src/node/server.ts]: Done here https://github.com/histoire-dev/histoire/pull/318/commits/8c9e082d4bff41aafb99306d0aa96947f545c8d5 🙂 !

File: packages/histoire/src/node/server.ts (hunk 2 above)
Comment (hugoattal) [reply packages/histoire/src/node/server.ts]: Done here https://github.com/histoire-dev/histoire/pull/318/commits/8c9e082d4bff41aafb99306d0aa96947f545c8d5 🙂 !

**Comment by Akryum** [comment]
What happens when we don't configure the port in histoire config? Will it be the normal vite port? I'd prefer it to be 6006 by default unless explicitly set in `histoireConfig.vite.server.port`.

**Comment by hugoattal** [comment]
Hum, I see... I updated the fix so that the port configured in the vite config file default to 6006.

File: packages/histoire/src/node/vite.ts [hunk 3]
```diff
@@ -105,9 +105,10 @@ async function mergeHistoireViteConfig (viteConfig: InlineConfig, ctx: Context)
 export async function getViteConfigWithPlugins (isServer: boolean, ctx: Context): Promise<InlineConfig> {
   const resolvedViteConfig = await resolveViteConfig(ctx)
 
-  const userViteConfig = await loadViteConfigFromFile({ command: ctx.mode === 'dev' ? 'serve' : 'build', mode: ctx.mode })
+  const userViteConfigFile = await loadViteConfigFromFile({ command: ctx.mode === 'dev' ? 'serve' : 'build', mode: ctx.mode })
+  const userViteConfig = mergeViteConfig(userViteConfigFile?.config ?? {}, { server: { port: 6006 } })
```
Comment (Akryum) [inline packages/histoire/src/node/vite.ts:109]: Should be the opposite, `mergeViteConfig` signature is `(defaults, overrides)`

**Review by Akryum — CHANGES_REQUESTED** [review]

File: packages/histoire/src/node/vite.ts (hunk 3 above)
Comment (hugoattal) [reply packages/histoire/src/node/vite.ts:109]: The `userViteConfigFile` is the config of Vite (not Histoire), so I believe this is what should be overridden with port 6006.
Else, Histoire will use the Vite defined port (if none is specified for Histoire) instead of the default 6006.

Basically here's how it works:

config: none
result: Histoire port is 6006

config: Vite port is 1234
result: Histoire port is 6006

config: Histoire port is 5678
result: Histoire port is 5678

config: Vite port is 1234 and Histoire port is 5678
result: Histoire port is 5678

Comment (Akryum) [reply packages/histoire/src/node/vite.ts:109]: Oh you're right, we merge histoire's vite config into it afterwards.

**Review by Akryum — APPROVED** [review]
