### PR TITLE
fix: Handle ESM Tailwindconfigs (fix #667)

### LINKED ISSUE #667: Support tailwind.config.ts
### Clear and concise description of the problem

Histoire will automatically detect your Tailwind CSS configuration and generate design system stories for you. But not if you make your `tailwind.config.js` with module.exports a `tailwind.config.ts` with export default.

### Suggested solution

Support both `tailwind.config.js` with module.exports and `tailwind.config.ts` with export default.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by schwarmco**
### Description

Fixes #667

When using ESMs `export default` instead of `module.exports` in `tailwind.config.{js,ts}` the tailwindConfig is nested in a `default` key which then incorrectly merges with tailwinds default config like this:

image

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [ ] If it's a new feature, provide a convincing reason to add it. *Ideally, you should open a suggestion issue first and have it approved before working on it.*
- [x] Read the [Contributing Guidelines](https://github.com/Akryum/histoire/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/Akryum/histoire/blob/main/CONTRIBUTING.md#pull-request-guidelines) and follow the [Commit Convention](https://github.com/Akryum/histoire/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export function tailwindTokens(options: TailwindTokensOptions = {}): Plugin {
       const { default: resolveConfig } = await import('tailwindcss/resolveConfig.js')
       const resolvedTailwindConfig = resolveConfig(tailwindConfig)
```
Comment (bahulneel) [inline packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts:29]:
```suggestion
      const resolvedTailwindConfig = resolveConfig(tailwindConfig.default ?? tailwindConfig)
```

File: packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts [hunk 2]
```diff
@@ -28,7 +28,7 @@ export function tailwindTokens(options: TailwindTokensOptions = {}): Plugin {
...
       const storyFile = api.path.resolve(api.pluginTempDir, 'Tailwind.story.js')
-      await api.fs.writeFile(storyFile, storyTemplate(resolvedTailwindConfig))
+      await api.fs.writeFile(storyFile, storyTemplate(resolvedTailwindConfig.default ?? resolvedTailwindConfig))
```
Comment (bahulneel) [inline packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts:31]:
```suggestion
      await api.fs.writeFile(storyFile, storyTemplate(resolvedTailwindConfig))
```

**Review by bahulneel — CHANGES_REQUESTED** [review]
The patch didn't work for me as the tailwind plugins (i.e. backgroundColours, etc.) that the tailwind storyTemplate expects were not being generated. After reading the documentation, I noticed that resolveConfig needed to run on with the tailwind config at the base of the imported object, not just the storyTemplate function.

**Comment by schwarmco** [comment]
Thank you for the feedback @bahulneel - i didn't run into that problem but i guess it depends on the ts environment you're in. As your suggestions were optional chained i've pulled them in the PR.

**Review by waldemarennsaed — COMMENTED** [review]
IMO that looks correct ... well done.

**Comment by waldemarennsaed** [comment]
Anything blocking from merging this?

**Comment by waldemarennsaed** [comment]
This would be nice to be merged. I have the current issue of:
- keeping a default tailwind config that overwrites tailwind colors and other theme-related stuff
- only working if exporting tailwind as `module.exports`

Then, I need to import my tailwind theme object in JavaScript, e.g. in one of my stories like that:

```vue
<script setup lang="ts">
import resolveConfig from 'tailwindcss/resolveConfig'
import tailwindConfig from '../../../../tailwind.config.js'

const fullConfig = resolveConfig(tailwindConfig)
</script>
```

Resulting in the following error:
Bildschirmfoto 2024-07-17 um 09 20 10
Bildschirmfoto 2024-07-17 um 09 22 49

I am pretty sure that this MR will fix this issue for me, since I will be able to keep a correct Tailwind Story and will be able to export my tailwind config as ESM.

**Comment by waldemarennsaed** [comment]
@schwarmco not intending to annoy anyone but ... any blockers on this? Or this be merged?

**Comment by schwarmco** [comment]
not annoying at all @waldemarennsaed - i'd love to get this merged too but i'm not a maintainer of histoire. i am actively using that patch on my projects

**Comment by waldemarennsaed** [comment]
@Akryum I don't know who else I could mention here - can you maybe bring some life to this MR? 🤓
