### PR TITLE
fix: #816 storyMatch traversing directories correctly

### LINKED ISSUE #816: storyMatch in histoire@1.0.0-alpha.4 does not work anymore
### Describe the bug

Using the `storyMatch` histoire configuration seems not to work anymore with `histoire@1.0.0-alpha.4`. The stories are simply not being found.

Removing the `storyMatch` config repairs it for me (I guess it just uses it's default paths then to find the stories).

### Reproduction

Install:
- `vite@7`
- `@vitejs/plugin-vue@6`
- `histoire@1.0.0-alpha.4`
- `@histoire/plugin-vue@1.0.0-alpha.4`

Use `storyMatch: ['src/**/*.story.vue']` in the `histoire.config.ts` config file.

See https://stackblitz.com/edit/histoire-vue3-starter-igc6chbk?file=histoire.config.ts

ℹ️ Removing `storyMatch` again, makes everything work well again.

### System Info

```shell
System:
    OS: macOS 26.0.1
    CPU: (12) arm64 Apple M4 Pro
    Memory: 1.18 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0 - /Users/waldemarenns/.nvm/versions/node/v22.20.0/bin/node
    npm: 10.9.3 - /Users/waldemarenns/.nvm/versions/node/v22.20.0/bin/npm
    Deno: 2.0.1 - /opt/homebrew/bin/deno
    Watchman: 2025.08.18.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 141.0.7390.108
    Edge: 141.0.3537.92
    Safari: 26.0.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://histoire.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by waldemarennsaed**
### Description

Adjusts the `/packages/histoire/src/node/stories.ts` file to fix traversing through directories to find matching stories for provided `storyMatch` paths.

`storyMatch` works again with relative paths like `storyMatch: ['src/**/*.story.vue']`.
Broken since Vite 6 upgrade in 40c16f2.

The implemented change was checking the currently traversed path for being relative or not. So relative paths are resolved correctly again.

Fixes #816 

How to test:

1. go to `/examples/vue3/histoire.config.ts`
2. add the config: `storyMatch: ['src/**/*.story.vue']`
3. notice how the stories are all there and resolved correctly
4. checkout the current main branch (before this fix) and test the same way -> most of the stories are not resolved

### Additional context

As there were no tests for `/packages/histoire/src/node/stories.ts`, I did not create a test-file, since _chokidar_ would require actual file-system interaction which goes beyond unit-testing.

### What is the purpose of this pull request? 

- [x] Bug fix
- [~] New Feature
- [~] Documentation update
- [~] Other

### Before submitting the PR, please make sure you do the following

- [~] If it's a new feature, provide a convincing reason to add it. *Ideally, you should open a suggestion issue first and have it approved before working on it.*
- [x] Read the [Contributing Guidelines](https://github.com/Akryum/histoire/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/Akryum/histoire/blob/main/CONTRIBUTING.md#pull-request-guidelines) and follow the [Commit Convention](https://github.com/Akryum/histoire/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [~] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by waldemarennsaed** [comment]
One issue I didn't notice, on it.

**Comment by hugoattal** [comment]
I admit, I'm not quite sure why it's fixing this 🤔... Isn't this equivalent to `return false;` ?

I can read this from the chokidar github (https://github.com/paulmillr/chokidar?tab=readme-ov-file#path-filtering)
> `ignored function`, regex, or path. Defines files/paths to be ignored. The whole relative or absolute path is tested, not just filename. If a function with two arguments is provided, it gets called twice per path - once with a single argument (the path), second time with two arguments (the path and the [`fs.Stats`](https://nodejs.org/api/fs.html#fs_class_fs_stats) object of that path).

**Comment by waldemarennsaed** [comment]
> I admit, I'm not quite sure why it's fixing this 🤔... Isn't this equivalent to `return false;` ?
> 
> I can read this from the chokidar github (https://github.com/paulmillr/chokidar?tab=readme-ov-file#path-filtering)
> 
> > `ignored function`, regex, or path. Defines files/paths to be ignored. The whole relative or absolute path is tested, not just filename. If a function with two arguments is provided, it gets called twice per path - once with a single argument (the path), second time with two arguments (the path and the [`fs.Stats`](https://nodejs.org/api/fs.html#fs_class_fs_stats) object of that path).

Yea I was a bit too fast, sorry 😄 It's not a fix yet. I'm on it

**Comment by waldemarennsaed** [comment]
@hugoattal I added a check with `{ relative }` from the `pathe` package which is already being used. It provides a function to easily check for a path being relative or not, through this method: https://nodejs.org/api/path.html#pathrelativefrom-to

I updated the PR description with instructions on how to test.

I also added a nested component + story to the `examples/vue3` example - if not required, I can remove it again.

File: packages/histoire/src/node/stories.ts [hunk 1]
```diff
@@ -48,14 +48,20 @@ export async function watchStories(newContext: Context) {
...
         return true
       }
-      if (context.config.storyMatch.some(pattern => micromatch.isMatch(path, pattern))) {
+      if (context.config.storyMatch.some(pattern => micromatch.isMatch(relativePath, pattern))) {
         return false
       }
 
-      return stats?.isFile()
+      // Allow directories to be traversed, only ignore files that don't match
+      return stats?.isFile() ?? false
```
Comment (hugoattal) [inline packages/histoire/src/node/stories.ts]: I still don't understand this 🤔... Is this just for typescript inference?
Isn't something like this a bit more readable? `return !!stats?.isFile()`

**Review by hugoattal — COMMENTED** [review]
Seems good to me, thanks a lot for the PR 😄 ! Just need a little information on the `?? false`, I'm not sure what this changes 🤔
